SELECT
    U.ID AS USER_ID
    , U.USER_NAME
    , C.ID AS CUSTOMER_ID
    , C.NAME AS CUSTOMER_NAME
    , C.ZIP_CODE
    , C.ADDRESS
    , C.PHONE
FROM
    USERS U INNER JOIN CUSTOMER C
        ON U.ID = C.USER_ID
WHERE
    1 = 1
    AND U.ID = $1
